name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-init-validate-plan:
    name: Terraform Init, Validate, and Plan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Replace with your Terraform version if different

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Create Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Upload the plan file as an artifact (optional)
      - name: Upload Plan File
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-init-validate-plan  # Runs after job 1 is successful

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Replace with your Terraform version if different

      # Step 3: Download the plan file from the previous job
      - name: Download Plan File
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .  # Download to the current working directory

      # Step 4: Apply Terraform Plan
      - name: Terraform Apply
        run: terraform apply tfplan
